export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const CART_ADD_PRODUCT = "CART_ADD_PRODUCT";
export const CART_REMOVE_PRODUCT = "CART_REMOVE_PRODUCT";
export const FILTER_PRODUCTS = "FILTER_PRODUCTS";

export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_INFO = "LOGIN_USER_INFO";
